### ISSUE TITLE
Please eliminate apostrophes in bank transfer field "Verwendungszweck"

### ISSUE THREAD

**Issue by monoclecat** [nspo/pybarsys#10]
In the billing email you provide a "Verwendungszweck" for the bank transfer, which is the display name of the user. 
My online banking does not support the apostrophes used to declare nicknames though. 
Nothing big, but I thought you might want to know.

**Comment by nspo** [comment]
Good idea, thanks.

On Feb 5, 2018 15:03, "Andy Delay" <notifications@github.com> wrote:

In the billing email you provide a "Verwendungszweck" for the bank
transfer, which is the display name of the user.
My online banking does not support the apostrophes used to declare
nicknames though.
Nothing big, but I thought you might want to know.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/nspo/pybarsys/issues/10>, or mute the thread

**Comment by monoclecat** [comment]
> Gültige Zeichen sind nur Buchstaben, Ziffern, Leerzeichen und die Zeichen . , + - /
